# Generated by Django 2.2.5 on 2019-11-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='directors',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre',
        ),
    ]
