# Generated by Django 2.2.5 on 2019-11-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191128_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-open_date', '-rate']},
        ),
    ]
