# Generated by Django 2.2.5 on 2019-11-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20191125_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worldcup',
        ),
    ]
