# Generated by Django 2.2.5 on 2019-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20191125_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='open_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.TextField(),
        ),
    ]
